version: '3.4'

services:
  spotify.api:
    image: ${DOCKER_REGISTRY-}spotifyapi
    build:
      context: .
      dockerfile: Spotify.API/Dockerfile
    environment: 
         - ASPNETCORE_ENVIRONMENT=Development
         - SpotifyConnectionString=Server=spotify;Database=Spotify; User id = sa ; password = Password.123;Trusted_Connection=False
    depends_on:
        - spotify
    ports:
        - "8000:80"
  spotify:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:     
        - SA_PASSWORD=Pa$$word
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"